authapp/urls.py
from django.conf.urls import url
from django.urls import path, include, re_path

import authapp.views as authapp

app_name = 'auth'

urlpatterns = [
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('login/', authapp.login, name='login'),
    # path('login/', authapp.Login.as_view(extra_context={'title': 'Авторизация'}), name='login'),
    # path('logout/', authapp.logout, name='logout'),
    path('register/applicant',
         authapp.ApplicantRegistration.as_view(extra_context={'title': 'Регистрация', 'reg_type': 'applicant'}),
         name='register_applicant'),
    path('register/company',
         authapp.CompanyRegistration.as_view(extra_context={'title': 'Регистрация', 'reg_type': 'company'}),
         name='register_company'),

    # re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),

]

doctorservice/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

appname = 'mainapp'

urlpatterns = [
    path('', include('mainapp.urls')),
    # path('auth/', include('authapp.urls', namespace='auth')),
    # path('company/', include('companyapp.urls', namespace='company')),
    # path('applicant/', include('applicantapp.urls', namespace='applicant')),
    path('doctor/', include('doctors.urls')),
    path('serviciu/', include('serviceapp.urls')),
    # path('auth/', include('authapp.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

authapp/models.py
from datetime import datetime, timedelta
from django.utils import timezone
import pytz
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models




from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

#manager for our custom model
class MyAccountManager(BaseUserManager):
    """
        This is a manager for Account class
        https://stackoverflow.com/questions/37308246/django-how-to-save-my-hashed-password
        save without hash
    """
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("Users must have an Emaill address")
        if not username :
            raise ValueError("Users must have an Username")
        user  = self.model(
                email=self.normalize_email(email),
                username=username,
            )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
                email=self.normalize_email(email),
                password=password,
                username=username,
            )
        user.is_admin = True
        user.is_staff=True
        user.is_superuser=True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    PROFILE = (
        ('Doctor', 'Doctor'),
        ('Company', 'Company'),
        ('Pacient', 'Pacient'),
        )
    profile_type = models.CharField(max_length=7, choices=PROFILE, default=PROFILE[0])
    birthday = models.IntegerField(verbose_name="Ziua de nastere", null=True, blank=True)
    phone = models.IntegerField(verbose_name="Telefon", null=True, blank=True, unique=True)
    user_about = models.TextField(verbose_name="Despre tine", null=True, blank=True)
    email = models.TextField(verbose_name="Email", unique=True, null=True)
    username = models.TextField(verbose_name="Username")
    # user_patronymic = models.CharField(verbose_name='Patronimic', max_length=150, null=True, blank=True)
    company_name = models.CharField("Numele Companiei", max_length=150, null=True, blank=True)
    company_about = models.TextField(verbose_name='Despre Companie', null=True, blank=True)
    company_main_business = models.CharField("Domeniu", max_length=150, null=True, blank=True)
    company_since = models.DateTimeField(verbose_name='Fondarea', null=True, blank=True)
    file = models.FileField(verbose_name='Foto', upload_to='avatars', blank=True)
    is_partner = models.BooleanField(verbose_name='Partener', blank=True, default=False)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = MyAccountManager()


    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin
    def has_module_perms(self, app_label ):
        return True

# class MyUser(AbstractUser):
#     DOCTOR = 2
#     HOSPITAL = 3
#     ROLE_CHOICES = (
#         (DOCTOR, 'Doctor'),
#         (HOSPITAL, 'Hospital'),
#     )
#     role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, null=True, blank=True)
#
#     def __str__(self):
#         return self.username

    # activation_key = models.CharField(max_length=128, blank=True)
    # activation_key_expires = models.DateTimeField(
    #     verbose_name='Актуальность ключа',
    #     default=(timezone.now() + timedelta(hours=48))
    # )

    # def is_activation_key_expired(self):
    #     if datetime.now(pytz.timezone(settings.TIME_ZONE)) <= self.activation_key_expires:
    #         return False
    #     else:
    #         return True

authapp/forms.py
import hashlib
import random

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from authapp.models import MyUser


# class UserLoginForm(AuthenticationForm):
#     class Meta:
#         model = User
#         fields = ('username', 'password')
#
#     def __init__(self, *args, **kwargs):
#         super(UserLoginForm, self).__init__(*args, **kwargs)
#         for field_name, field in self.fields.items():
#             field.widget.attrs['class'] = 'form-control'
#             field.help_text = None


class ApplicantRegistrationForm(UserCreationForm):
    class Meta:
        model = MyUser
        fields = ('profile_type', 'phone', 'email')

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        del self.fields['password2']
        # self.fields.pop('password1')
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = None
            # del self.fields['password2']
            # self.fields['password1'].help_text = "azaza"
            # self.fields['username'].help_text = None


    def save(self, **kwargs):
        user = super(ApplicantRegistrationForm, self).save()

        user.is_active = False
        # salt = hashlib.sha1(str(random.random()).encode('utf8')).hexdigest()[:6]
        # user.activation_key = hashlib.sha1((user.email + salt).encode('utf8')).hexdigest()
        user.save()

        return user


class CompanyRegistrationForm(UserCreationForm):
    class Meta:
        model = MyUser
        fields = ('username', 'company_name', 'password1', 'password2', 'email',
                  'company_main_business', 'company_since', 'company_about', 'file')

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = None

    def save(self, **kwargs):
        user = super(CompanyRegistrationForm, self).save()

        user.is_active = False
        # salt = hashlib.sha1(str(random.random()).encode('utf8')).hexdigest()[:6]
        # user.activation_key = hashlib.sha1((user.email + salt).encode('utf8')).hexdigest()
        user.save()

        return user

authapp/views.py
from django.conf import settings
from django.contrib.auth.views import LoginView
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.contrib import auth
from django.views.generic import CreateView

# from authapp.forms import UserLoginForm, ApplicantRegistrationForm, CompanyRegistrationForm
from authapp.forms import ApplicantRegistrationForm, CompanyRegistrationForm
from authapp.models import MyUser


def verify(request, email, activation_key):
    try:
        user = MyUser.objects.get(email=email)
        if user.activation_key == activation_key and not user.is_activation_key_expired():
            user.is_active = True
            user.save()
            auth.login(request, user)
            return render(request, 'authapp/verification.html')
        else:
            print(f'error activation user: {user}')
            return render(request, 'authapp/verification.html')
    except Exception as e:
        print(f'error activation user: {e.args}')
        return HttpResponseRedirect(reverse('main:main'))


def send_verify_mail(user):
    verify_link = reverse('auth:verify', args=[user.email, user.activation_key])

    title = f'Подтверждение учетной записи {user.username}'

    message = f'Для подтверждения учетной записи {user.username} на сайте GB группы 2/2' \
              f'перейдите по ссылке: \n{settings.DOMAIN_NAME}{verify_link}'
    # print(message)

    return send_mail(title, message, settings.EMAIL_HOST_USER, [user.email], fail_silently=False)


# class Login(LoginView):
#     template_name = 'authapp/login.html'
#     form_class = UserLoginForm


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main:main'))


class ApplicantRegistration(CreateView):
    form_class = ApplicantRegistrationForm
    success_url = reverse_lazy('auth:login')
    template_name = 'authapp/register.html'

    def form_valid(self, form):
        if self.request.method == 'POST':
            register_form = ApplicantRegistrationForm(self.request.POST, self.request.FILES)
            if register_form.is_valid():
                register_form.save()
                # if send_verify_mail(user):
                #     print('email sending success')
                # else:
                #     print('error while email sending')
                return HttpResponseRedirect(reverse('main'))
        else:
            register_form = ApplicantRegistrationForm()

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['reg_type'] = self.kwargs['reg_type']
    #     return context


class CompanyRegistration(CreateView):
    form_class = CompanyRegistrationForm
    success_url = reverse_lazy('auth:login')
    template_name = 'authapp/register.html'

    def form_valid(self, form):
        if self.request.method == 'POST':
            register_form = CompanyRegistrationForm(self.request.POST, self.request.FILES)
            if register_form.is_valid():
                obj = register_form.save()
                obj.is_staff = True
                user = register_form.save()
                if send_verify_mail(user):
                    print('email sending success')
                else:
                    print('error while email sending')
                return HttpResponseRedirect(reverse('auth:login'))
        else:
            register_form = CompanyRegistrationForm()

templates/authapp/login.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}


    <div class="card mx-auto shadow-sm" style="width: 400px;" id="loginForm">
        <!-- <img src="" class="card-img-top" alt="..."> -->
        <div class="card-body align-items-center align-content-center">
            <h5 class="card-title">Авторизация</h5>
            <!-- <h6 class="card-subtitle mb-2 text-muted ">Card subtitle</h6> -->
            <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}

                {#                {% if form.errors %}#}
                {#                    {% for field in form %}#}
                {#                        {% for error in field.errors %}#}
                {#                            <p> {{ error }} </p>#}
                {#                        {% endfor %}#}
                {#                    {% endfor %}#}
                {#                {% endif %}#}
                {#                {% for field in form %}#}
                {#                    {{ field.errors }}#}
                {#                {% endfor %}#}

                <div class="d-grid">
                    <button class="btn btn-primary d-block"
                            type="submit" role="button">Войти
                    </button>
                </div>
            </form>
            <p class="mt-4">Регистрация</p>
            <div class="d-grid gap-2">
                <a class="btn btn-outline-secondary btn-sm " href="{% url 'auth:register_applicant' %}"
                   role="button">Соискателя</a>
                <a class="btn btn-outline-secondary btn-sm " href="{% url 'auth:register_company' %}"
                   role="button">Работодателя</a>
            </div>

        </div>
    </div>


{% endblock %}

templates/authapp/register.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}

    <div class="card mx-auto shadow-sm" style="width: 400px;" id="loginForm">
        <!-- <img src="" class="card-img-top" alt="..."> -->
        <div class="card-body align-items-center align-content-center">
            <h5 class="card-title">Регистрация</h5>

            <form enctype="multipart/form-data" class="form-horizontal"
                    {% if reg_type == 'applicant' %}
                  action="{% url 'auth:register_applicant' %}"
                    {% else %}
                  action="{% url 'auth:register_company' %}"
                    {% endif %}
                  method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <br>
                <div class="d-grid">
                    <input class="btn btn-secondary" type="submit" value="Регистрация">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/authapp/verification.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}

    {% if user %}
        <h3>Поздравляем!</h3>
        <br>
        <h4>Пользователь {{ user.username }} подтвержден.</h4>
    {% else %}
        <h3>Верификация не пройдена.</h3>
    {% endif %}
    <br>
    <button class="btn btn-round form-control">
        <a href="{% url 'main' %}" class="">на главную</a>
    </button>

{% endblock %}